# Generated by Django 2.0 on 2018-05-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtcapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='rtc_id',
            field=models.CharField(max_length=10000000000000000000000000000000000000000000),
        ),
    ]
